// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptcbxthdvrksaebydkjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0Y2J4dGhkdnJrc2FlYnlka2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3Mjk2NDIsImV4cCI6MjA3MTMwNTY0Mn0.B0eOKOUwZSC6DINOdUrCUDSFbrabm7bRtQZ-PW-ploE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});